import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "teacher dashboard",
  // description: "Generated by create next app",
};

function layout() {
  return <div>layout</div>;
}

export default layout;
