import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "@/layout/SideMenu";
import Header from "@/layout/Header";
import Providers from "./Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "home dashboard",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="w-full h-screen flex items-start justify-start">
            <SideMenu />
            <section className="max-md:w-full w-4/5 h-full">
              <Header />
              {children}
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
